ask_aaron/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.auth.tokens import default_token_generator
from django.urls import reverse_lazy
from django.contrib.auth.forms import SetPasswordForm
from user.views import CustomPasswordResetConfirmView
from django.contrib.auth.decorators import login_required
from django.contrib import admin
from django.views.defaults import page_not_found

from user.admin import admin_view
admin.site.admin_view = admin_view

import ask_chat
from ask_chat import views

urlpatterns = [
    url(r'^admin/login/', page_not_found),
    url(r'^admin/', admin.site.urls),
    # path('admin/', admin.site.urls),
    path('', ask_chat.views.index, name='index'),
    path('ask/', include('ask_chat.urls', namespace='ask_chat')),
    path('user/', include('user.urls', namespace='user')),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='ask_chat/index.html'
         ),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='ask_chat/index.html'
         ),
         name='password_reset_complete'),

]


handler404 = 'user.views.custom_page_not_found_view'
# handler500 = 'my_app_name.views.custom_error_view'
# handler403 = 'my_app_name.views.custom_permission_denied_view'
# handler400 = 'my_app_name.views.custom_bad_request_view'

ask_chat/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import GPTChatView
app_name = 'ask_chat'

urlpatterns = [
    # path('ask-anything/', ask_anything, name='ask_anything'),
    path('ask_anything/', login_required(GPTChatView.as_view()), name='ask_anything'),
]

user/urls.py
from django.conf.urls import url
from django.urls import path

from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from .views import login, register, logout, activate, password_reset_request
app_name = 'user'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout, name='logout'),

    path('activate/<uidb64>/<token>', activate, name='activate'),

    path('password_reset/', password_reset_request, name='password_reset'),

    # path('password-reset/',
    #      auth_views.PasswordResetView.as_view(
    #          template_name='user/password_reset.html',
    #          email_template_name='user/reset_password_email.html',
    #          success_url = reverse_lazy('index')
    #      ),
    #      name='reset_password'),
    #
    # path(r'reset/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(
    #          template_name='user/password_reset_confirm.html',
    #      ),
    #      name='password_reset_confirm'),
    #
    # path('password-reset/done/',
    #      auth_views.PasswordResetDoneView.as_view(
    #          template_name='ask_chat/index.html'
    #      ),
    #      name='password_reset_done'),
    #
    # # path('password-reset-confirm/<uidb64>/<token>/',
    # #      auth_views.PasswordResetConfirmView.as_view(
    # #          template_name='user/password_reset_confirm.html'
    # #      ),
    # #      name='password_reset_confirm'),
    #
    # path('password-reset-complete/',
    #      auth_views.PasswordResetCompleteView.as_view(
    #          template_name='ask_chat/index.html'
    #      ),
    #      name='password_reset_complete'),

    # path('password_change', password_change, name='password_change'),
    # path('password_reset', password_reset_request, name='password_reset'),
    # path('reset/<uidb64>/<token>', passwordResetConfirm, name='password_reset_confirm')

    # path('password_reset/', auth_views.PasswordResetView.as_view(
    #     email_template_name='user/reset_password_email.html',
    #     template_name='user/password_reset.html',
    #     success_url=reverse_lazy('user:password_reset_done'),
    #
    # ), name='password_reset'),
    #
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    #
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
    #     template_name='user/password_reset_confirm.html'
    # ), name='password_reset_confirm'),
    #
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

ask_chat/models.py
from django.db import models

# Create your models here.

ask_chat/forms.py
from django import forms
from .models import *


class ChatForm(forms.Form):
    TEMPCHOICES = (('5','TEMPERATURE'),('1','0.1'),('2','0.2'),('3','0.3'),('4','0.4'),('5','0.5'),('6','0.6'),('7','0.7'),('8','0.8'),('9','0.9'),('10','1.0'))
    CONTEXTCHOICES = (('YES','CONTEXT'),('YES','YES'),('NO','NO'))
    temperature = forms.ChoiceField(choices=TEMPCHOICES, widget=forms.Select(attrs=
        {'class': 'select-temp w-node-b91f7330-36d2-bf4e-fc1a-d66e8233fbd4-9d78feda w-select',
         'id': 'field-2',
         'name': 'temperature',
         'placeholder': 'TEMPERATURE',
         'data-name':'Temperature'
         }),required=False)

    context = forms.ChoiceField(choices=CONTEXTCHOICES, widget=forms.Select(attrs=
    {'class': 'select-temp w-node-b91f7330-36d2-bf4e-fc1a-d66e8233fbd4-14932c8f w-select',
     'id': 'field-2',
     'name': 'context',
     'placeholder': 'CONTEXT',
     'data-name': 'Context'
     }),required=False)

    answer = forms.CharField(widget=forms.Textarea(attrs=
    {'class': '',
     'id': 'name',
     'name': 'answer',
     'data-name': 'Answer',
     'style': 'border:none; outline:none; border-style:none; border-color:Transparent; overflow:auto; opacity: 1;',
     'rows':2
     }),required=False)

    response = forms.CharField(widget=forms.Textarea(attrs={
        'style': 'width:450px; border:none; outline:none; border-style:none; border-color:Transparent; overflow:auto; opacity: 1;',
        # 'rows': 2,
    }))
    question = forms.CharField(widget=forms.TextInput(attrs=
    {'class': 'subscribe-form-input w-node-_67e93785-6278-b925-a661-4f92cae5470d-9d78feda w-input',
     'maxlength' : '10000',
     'placeholder': 'QUESTION',
     'id': 'Subscriber-Email-2',
     'name': 'question',
     'data-name': 'Question'
     }),required=False)

ask_chat/views.py
import openai
import asyncio
import aiohttp
import requests

from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.decorators import login_required
from ask_chat.forms import *
from django.views.generic import TemplateView
from ask_chat.utils import getCHAT
from asgiref.sync import async_to_sync, sync_to_async
from django.http import JsonResponse
from django.core import serializers

def index(request):
    return render(request, 'ask_chat/index.html')

class GPTChatView(TemplateView):
    template_name = 'ask_chat/ask-anything.html'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.form = ChatForm()

    def get_context_data(self, *args, **kwargs):
        context = super(GPTChatView, self).get_context_data(**kwargs)
        context['form'] = self.form
        context['api_response'] = None
        context['user_question'] = None
        return context

    def post(self, request, *args, **kwargs):
        if self.request.is_ajax and self.request.method == "POST":
            context = self.get_context_data(**kwargs)
            temperature = request.POST.get('temperature')
            context_present = request.POST.get('context')
            question = request.POST.get('question')
            answer = request.POST.get('answer')
            try:
                if context_present == "YES":
                    prompt = f"{answer}USER: {question}"
                    # prompt = f"{question}"
                    response = getCHAT(prompt, temperature)
                    dialog = response.strip()
                    self.form = ChatForm({
                        'answer': f"{prompt}\nAI:{dialog}\n",
                        'context': context,
                        'temperature': temperature,
                    })
                    context['api_response'] = response

                else:
                    prompt = question
                    response = getCHAT(prompt, temperature)
                    dialog = response.strip()
                    self.form = ChatForm({
                        'answer': f"AI: {dialog}",
                        'context': context,
                        'temperature': temperature,
                    })
                    context['api_response'] = response

#   -  openai.error.RateLimitError: The server had an error while processing your request. Sorry about that!
#   -  openai.error.ServiceUnavailableError: The server is overloaded or not ready yet.

            except openai.error.RateLimitError:
                context['api_response'] = 'Too Many Requests. Wait!'

            context['form'] = self.form
            context['user_question'] = question
            return JsonResponse({'api_response': context['api_response'], 'user_question': context['user_question']})
            # return self.render_to_response(context)

        return super().post(request, *args, **kwargs)

ask_chat/templates/ask_chat/ask-anything.html
{% load static %}
<!DOCTYPE html><!--  This site was created in Webflow. https://www.webflow.com  -->
<!--  Last Published: Wed Feb 01 2023 08:16:07 GMT+0000 (Coordinated Universal Time)  -->
<html data-wf-page="63cb76e2d7632eb7e133dd37" data-wf-site="63c71f3c4e03650f2016f4d7" lang="en">
<head>
    <meta charset="utf-8">
    <title>AskAaron.app your AI-powered Lawyer | Lawsity</title>
    <meta content="AskAaron.app is your AI-powered Lawyer developed by Lawsity, capable of generating human-like answers." name="description"/>
    <meta content="AskAaron.app your AI-powered Lawyer | Lawsity" property="og:title"/>
    <meta content="AskAaron.app is your AI-powered Lawyer developed by Lawsity, capable of generating human-like answers." property="og:description"/>
    <meta content="https://askaaron.app/static/images/ask-aaron-logo.png" property="og:image"/>
    <meta content="AskAaron.app your AI-powered Lawyer | Lawsity" property="twitter:title"/>
    <meta content="AskAaron.app is your AI-powered Lawyer developed by Lawsity, capable of generating human-like answers." property="twitter:description"/>
    <meta content="https://askaaron.app/static/images/ask-aaron-logo.png" property="twitter:image"/>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta property="og:type" content="website"/>
    <meta content="summary_large_image" name="twitter:card"/>
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon"/>
    <link href="{% static 'images/ask-aaron-logo.png' %}" rel="apple-touch-icon"/>
    <!-- meta title -->
    <meta content="AskAaron.app your AI-powered Lawyer | Lawsity" property="twitter:title">
    <!-- end meta title -->
    <!-- meta description -->
    <meta content="AskAaron.app is your AI-powered Lawyer developed by Lawsity, capable of generating human-like answers." property="twitter:description">
    <!-- end meta description -->
    <!-- meta optional -->
    <meta property="og:site_name" content="AskAaron.app"/>
    <link rel="shortcut icon" type="image/x-icon" href=" {% static 'images/favicon.ico' %}"/>
    <meta property="og:image" content="{% static 'images/ask-aaron-logo.png' %}"/>
    <meta property="og:image:secure_url" content="{% static 'images/ask-aaron-logo.png' %}"/>
    <meta name="twitter:image" content="{% static 'images/ask-aaron-logo.png' %}"/>
    <!-- end meta optional -->
    <!-- meta image -->
        <meta property="og:image" content="{% static 'images/ask-aaron-logo.png' %}">
    <meta property="og:image:secure_url" content="{% static 'images/ask-aaron-logo.png' %}">
    <meta name="twitter:image" content="{% static 'images/ask-aaron-logo.png' %}">
    <!-- end meta image -->
    <!-- end meta script -->
    <meta property="og:type" content="website">
    <meta content="summary_large_image" name="twitter:card">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <!--  meta default  -->
    <meta property="og:type" content="website">
    <meta content="summary_large_image" name="twitter:card">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta property="og:locale" content="en_US">
    <meta property="og:site_name" content="askaaron.app">
    <meta name="theme-color" content="#545974">
    <link href="{% static 'css/normalize.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/webflow.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/chatgpt-876e64.webflow.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/loader.css' %}" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
    <script type="text/javascript">
        WebFont.load({
        google: {
            families: ["Rubik:200,300,400,500,600,700"]
        }
        });
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <!-- [if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script><![endif] -->
    <script type="text/javascript">
        ! function(o, c) {
        var n = c.documentElement,
            t = " w-mod-";
        n.className += t + "js", ("ontouchstart" in o || o.DocumentTouch && c instanceof DocumentTouch) && (n.className += t + "touch")
        }(window, document);
    </script>
    <link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">
    <link href="{% static 'images/webclip.png' %}" rel="apple-touch-icon">
</head>
<body class="body">
  <div data-animation="default" data-collapse="medium" data-duration="400" data-easing="ease" data-easing2="ease" role="banner" class="navbar-2 w-nav">
    <div class="container-4 w-container">
      <nav role="navigation" class="nav-menu w-nav-menu">

        <a href="{% url 'user:logout' %}" class="nav-link w-nav-link">Log Out</a>

      </nav>
      <div class="menu-button-2 w-nav-button">
        <div class="w-icon-nav-menu"></div>
      </div>
      <a href="#" aria-current="page" class="brand w-nav-brand w--current">
        <div class="text-block-2">ASK AARON</div><img src="{% static 'images/logo-icon-pink.svg' %}" alt="logo icon" class="image-2">
      </a>
    </div>
  </div>
  <div class="section-answer wf-section">
    <div class="container w-container">
      <div class="questiondiv">
        <div class="rich-text-block w-richtext">
            <p id="user_question"></p>
            {{ user_question|default_if_none:""|capfirst }}
            <div style="display: none;">
                {{ form.answer }}
            </div>
        </div>
      </div>
      <div class="responsediv">
        <div class="rich-text-block w-richtext">
            <p id="api_response"></p>
            {{ api_response|default_if_none:""|linebreaks }}
        </div>
      </div>
    </div>
  </div>
  <div class="section wf-section">
{#      Loader -----------------------------------------------#}
        <div class="loader">
            <div class="loader_inner"></div>
        </div>
{#          -------------------------------------------------------#}
    <div class="container w-container">
      <div class="form-block w-form">
        <form action="{% url 'ask_chat:ask_anything' %}" id="email-form" name="email-form" data-name="Email Form" method="post" class="form-2">
            {% csrf_token %}
          <div class="w-layout-grid grid-5">
                {{ form.temperature }}
              {{ form.context }}
          </div>
          <div class="w-layout-grid grid-2">
              {{ form.question }}
              <input type="submit" value="Ask" data-wait="Please wait..." id="w-node-_67e93785-6278-b925-a661-4f92cae5470e-9d78feda" class="submit-button-3 w-button">
            <div id="w-node-_6631eeeb-ea6e-dcc6-d053-3ab58117e430-9d78feda" class="div-block-3">
              <ul role="list" class="list">
                <li class="list-item"><span class="text-span">Higher temperature</span> will produce more varied and unpredictable results.<br></li>
                <li class="list-item"><span class="text-span-2">Lower temperature</span> will produce more conservative and predictable results.<br></li>
                <li class="list-item"><span class="text-span-3">Context</span>: Remember or not previous answer</li>
              </ul>
            </div>
          </div>
        </form>
        <div class="w-form-done">
          <div>Thank you! Your submission has been received!</div>
        </div>
        <div class="w-form-fail">
          <div>Oops! Something went wrong while submitting the form.</div>
        </div>
      </div>
      <div class="div-block">
        <div class="text-footer">Copyright © 2023 <span class="text-span-4">AskAaron.app </span>/Lawsity LLC | All Right Reserved.</div>
      </div>
    </div>
  </div>
  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=63c71f3c4e03650f2016f4d7" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="{% static 'js/webflow.js' %}" type="text/javascript"></script>
  <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->
  <script>
      $(document).ready(function() {
    $("#email-form").submit(function(event) {
        event.preventDefault();

        $(".loader").show();
        var form_data = $(this).serialize();


        $.ajax({
            url: "{% url 'ask_chat:ask_anything' %}",
            type: 'post',
            data: form_data,
            success: function(response) {
                console.log(response);
                var encodedResponse = response.api_response.replace(/\r\n/g, '\\r\\n').replace(/\n/g, '\n');
                var encodedResponse = response.api_response.replace(/\n/g, '<br>');
                $("#api_response").html(encodedResponse);
                $("#user_question").html(response.user_question);
                $(".loader").hide();
            },
            error: function(xhr, status, error) {
                console.log(xhr.responseText);
                $(".loader").hide();
            }
        });
    });
});
  </script>
</body>
</html>

{#{% extends 'ask_chat/exemple.html' %}#}
{#{% load static %}#}
{##}
{#{% block css %}#}
{#    <link href="{% static 'css/loader.css' %}" rel="stylesheet" type="text/css">#}
{#{% endblock %}#}
{##}
{#{% block header %}#}
{#    {% include 'ask_chat/include/navBar.html' %}#}
{#{% endblock %}#}
{##}
{#{% block content %}#}
{#    <div class="section-answer wf-section">#}
{#    <div class="container w-container">#}
{#      <div class="questiondiv">#}
{#        <div class="rich-text-block w-richtext">#}
{#            <p id="user_question"></p>#}
{#            {{ user_question|default_if_none:""|capfirst }}#}
{#        </div>#}
{#      </div>#}
{#      <div class="responsediv">#}
{#        <div class="rich-text-block w-richtext" id="api_response">#}
{#            <p id="api_response"></p>#}
{#            {{ api_response|default_if_none:""|linebreaks }}#}
{#        </div>#}
{#      </div>#}
{#    </div>#}
{#  </div>#}
{#  <div class="section wf-section">#}
{#      Loader -----------------------------------------------#}
{#        <div class="loader">#}
{#            <div class="loader_inner"></div>#}
{#        </div>#}
{#      -------------------------------------------------------#}
{#    <div class="container w-container">#}
{#      <div class="form-block w-form">#}
{#        <form action="{% url 'ask_chat:ask_anything' %}" id="email-form" name="email-form" data-name="Email Form" method="post" class="form-2">#}
{#            {% csrf_token %}#}
{#          <div class="w-layout-grid grid-5">#}
{#                {{ form.temperature }}#}
{#              {{ form.context }}#}
{#          </div>#}
{#          <div class="w-layout-grid grid-2">#}
{#              {{ form.question }}#}
{#              <input type="submit" value="Ask" data-wait="Please wait..." id="w-node-_67e93785-6278-b925-a661-4f92cae5470e-9d78feda" class="submit-button-3 w-button">#}
{#            <div id="w-node-_6631eeeb-ea6e-dcc6-d053-3ab58117e430-9d78feda" class="div-block-3">#}
{#              <ul role="list" class="list">#}
{#                <li class="list-item"><span class="text-span">Higher temperature</span> will produce more varied and unpredictable results.<br></li>#}
{#                <li class="list-item"><span class="text-span-2">Lower temperature</span> will produce more conservative and predictable results.<br></li>#}
{#                <li class="list-item"><span class="text-span-3">Context</span>: Remember or not previous answer</li>#}
{#              </ul>#}
{#            </div>#}
{#          </div>#}
{#        </form>#}
{#        <div class="w-form-done">#}
{#          <div>Thank you! Your submission has been received!</div>#}
{#        </div>#}
{#        <div class="w-form-fail">#}
{#          <div>Oops! Something went wrong while submitting the form.</div>#}
{#        </div>#}
{#      </div>#}
{#      <div class="div-block">#}
{#        <div class="text-footer">Copyright © 2023 <span class="text-span-4">AskAaron.app </span>/Lawsity LLC | All Right Reserved.</div>#}
{#      </div>#}
{#    </div>#}
{#  </div>#}
{#{% endblock %}#}
{##}
{#{% block script %}#}
{#    <script>#}
{#      $(document).ready(function() {#}
{#    $("#email-form").submit(function(event) {#}
{#        event.preventDefault();#}
{##}
{#        $(".loader").show();#}
{#        var form_data = $(this).serialize();#}
{##}
{##}
{#        $.ajax({#}
{#            url: "{% url 'ask_chat:ask_anything' %}",#}
{#            type: 'post',#}
{#            data: form_data,#}
{#            success: function(response) {#}
{#                console.log(response);#}
{#                var encodedResponse = response.api_response.replace(/\r\n/g, '\\r\\n').replace(/\n/g, '\n');#}
{#                var encodedResponse = response.api_response.replace(/\n/g, '<br>');#}
{#                $("#api_response").html(encodedResponse);#}
{#                $("#user_question").html(response.user_question);#}
{#                $(".loader").hide();#}
{#            },#}
{#            error: function(xhr, status, error) {#}
{#                console.log(xhr.responseText);#}
{#                $(".loader").hide();#}
{#            }#}
{#        });#}
{#    });#}
{#});#}
{#  </script>#}
{#{% endblock %}#}

ask_chat/templates/ask_chat/base.html
{% load static %}
<!DOCTYPE html><!--  This site was created in Webflow. https://www.webflow.com  -->
<!--  Last Published: Tue Jan 24 2023 07:48:52 GMT+0000 (Coordinated Universal Time)  -->
<html data-wf-page="63cb76e2d7632eb7e133dd37" data-wf-site="63c71f3c4e03650f2016f4d7" lang="en">
<meta charset="utf-8">
<title>AskAaron.app your AI-powered Lawyer | Lawsity</title>
<meta content="AskAaron.app is your AI-powered Lawyer developed by Lawsity, capable of generating human-like answers." name="description"/>
<meta content="AskAaron.app your AI-powered Lawyer | Lawssity" property="og:title"/>
<meta content="AskAaron.app is your AI-powered Lawyer developed by Lawsity, capable of generating human-like answers." property="og:description"/>
<meta content="https://askaaron.app/static/images/ask-aaron-logo.png" property="og:image"/>
<meta content="AskAaron.app your AI-powered Lawyer | Lawsity" property="twitter:title"/>
<meta content="AskAaron.app is your AI-powered Lawyer developed by Lawsity, capable of generating human-like answers." property="twitter:description"/>
<meta content="https://askaaron.app/static/images/ask-aaron-logo.png" property="twitter:image"/>
<meta content="width=device-width, initial-scale=1" name="viewport">
<meta property="og:type" content="website"/>
<meta content="summary_large_image" name="twitter:card"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<link href="https://askaaron.app/static/images/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="https://askaaron.app/static/images/ask-aaron-logo.png" rel="apple-touch-icon"/>
    <!-- meta title -->
    <meta content="AskAaron.app your AI-powered Lawyer | Lawsity" property="twitter:title">
    <!-- end meta title -->
    <!-- meta description -->
    <meta content="AskAaron.app is your AI-powered Lawyer developed by Lawsity, capable of generating human-like answers." property="twitter:description">
    <!-- end meta description -->
    <!-- meta optional -->
    <meta property="og:site_name" content="AskAaron.app"/>
<link rel="shortcut icon" type="image/x-icon" href="https://askaaron.app/static/images/favicon.ico"/>
<meta property="og:image" content="https://askaaron.app/static/images/ask-aaron-logo.png"/>
<meta property="og:image:secure_url" content="https://askaaron.app/static/images/ask-aaron-logo.png"/>
<meta name="twitter:image" content="https://askaaron.app/static/images/ask-aaron-logo.png"/>
    <!-- end meta optional -->
    <!-- meta image -->
        <meta property="og:image" content="https://askaaron.app/static/images/ask-aaron-logo.png">
    <meta property="og:image:secure_url" content="https://askaaron.app/static/images/ask-aaron-logo.png">
    <meta name="twitter:image" content="https://askaaron.app/static/images/ask-aaron-logo.png">
    <!-- end meta image -->
    <!-- end meta script -->
    <meta property="og:type" content="website">
    <meta content="summary_large_image" name="twitter:card">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <!--  meta default  -->
    <meta property="og:type" content="website">
    <meta content="summary_large_image" name="twitter:card">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta property="og:locale" content="en_US">
    <meta property="og:site_name" content="askaaron.app">
    <meta name="theme-color" content="#545974">
    <link href="{% static 'css/normalize.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/webflow.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/chatgpt-876e64.webflow.css' %}" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
    <script type="text/javascript">
        WebFont.load({
        google: {
            families: ["Rubik:200,300,400,500,600,700"]
        }
        });
    </script>
    <!-- [if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script><![endif] -->
    <script type="text/javascript">
        ! function(o, c) {
        var n = c.documentElement,
            t = " w-mod-";
        n.className += t + "js", ("ontouchstart" in o || o.DocumentTouch && c instanceof DocumentTouch) && (n.className += t + "touch")
        }(window, document);
    </script>
    <link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">
    <link href="{% static 'images/webclip.png' %}" rel="apple-touch-icon">
</head>
<body class="body-2">


    {% block content %} {% endblock %}

  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=63c71f3c4e03650f2016f4d7" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="{% static 'js/webflow.js' %}" type="text/javascript"></script>
  <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->
</body>
</html>