ask_aaron/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.auth.tokens import default_token_generator
from django.urls import reverse_lazy
from django.contrib.auth.forms import SetPasswordForm
from user.views import CustomPasswordResetConfirmView
from django.contrib.auth.decorators import login_required
from django.contrib import admin
from django.views.defaults import page_not_found

from user.admin import admin_view
admin.site.admin_view = admin_view

import ask_chat
from ask_chat import views

urlpatterns = [
    url(r'^admin/login/', page_not_found),
    url(r'^admin/', admin.site.urls),
    # path('admin/', admin.site.urls),
    path('', ask_chat.views.index, name='index'),
    path('ask/', include('ask_chat.urls', namespace='ask_chat')),
    path('user/', include('user.urls', namespace='user')),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='ask_chat/index.html'
         ),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='ask_chat/index.html'
         ),
         name='password_reset_complete'),

]


handler404 = 'user.views.custom_page_not_found_view'
# handler500 = 'my_app_name.views.custom_error_view'
# handler403 = 'my_app_name.views.custom_permission_denied_view'
# handler400 = 'my_app_name.views.custom_bad_request_view'

user/urls.py
from django.conf.urls import url
from django.urls import path

from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from .views import login, register, logout, activate, password_reset_request
app_name = 'user'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout, name='logout'),

    path('activate/<uidb64>/<token>', activate, name='activate'),

    path('password_reset/', password_reset_request, name='password_reset'),

    # path('password-reset/',
    #      auth_views.PasswordResetView.as_view(
    #          template_name='user/password_reset.html',
    #          email_template_name='user/reset_password_email.html',
    #          success_url = reverse_lazy('index')
    #      ),
    #      name='reset_password'),
    #
    # path(r'reset/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(
    #          template_name='user/password_reset_confirm.html',
    #      ),
    #      name='password_reset_confirm'),
    #
    # path('password-reset/done/',
    #      auth_views.PasswordResetDoneView.as_view(
    #          template_name='ask_chat/index.html'
    #      ),
    #      name='password_reset_done'),
    #
    # # path('password-reset-confirm/<uidb64>/<token>/',
    # #      auth_views.PasswordResetConfirmView.as_view(
    # #          template_name='user/password_reset_confirm.html'
    # #      ),
    # #      name='password_reset_confirm'),
    #
    # path('password-reset-complete/',
    #      auth_views.PasswordResetCompleteView.as_view(
    #          template_name='ask_chat/index.html'
    #      ),
    #      name='password_reset_complete'),

    # path('password_change', password_change, name='password_change'),
    # path('password_reset', password_reset_request, name='password_reset'),
    # path('reset/<uidb64>/<token>', passwordResetConfirm, name='password_reset_confirm')

    # path('password_reset/', auth_views.PasswordResetView.as_view(
    #     email_template_name='user/reset_password_email.html',
    #     template_name='user/password_reset.html',
    #     success_url=reverse_lazy('user:password_reset_done'),
    #
    # ), name='password_reset'),
    #
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    #
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
    #     template_name='user/password_reset_confirm.html'
    # ), name='password_reset_confirm'),
    #
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

class CustomUserManager(BaseUserManager):
    def _create_user(self, email, password, full_name, **extra_field):
        if not email:
            raise ValueError("Email must be provided")
        if not password:
            raise ValueError("Password is not provided")

        user = self.model(
            email=self.normalize_email(email),
            full_name=full_name,
            **extra_field
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, full_name, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(email, password, full_name, **extra_fields)

    def create_superuser(self, email, password, full_name, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(email, password, full_name, **extra_fields)
class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(db_index=True, unique=True, max_length=254)
    full_name = models.CharField(max_length=240)

    is_staff = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name']

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

user/forms.py
from django import forms
from django.utils.translation import gettext, gettext_lazy as _
from django.core.exceptions import ValidationError
from django.contrib.auth import (
    authenticate, get_user_model, password_validation,
)

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordResetForm, SetPasswordForm
from .models import User

class UserLoginForm(AuthenticationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your Email'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password'
    }))

    class Meta:
        model = User
        fields = ('email', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'text-field-imput w-input'

class UserRegistrationForm(UserCreationForm):
    full_name = forms.CharField(max_length= 256, widget=forms.TextInput(attrs={
        'placeholder': 'Your Name'
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your Email'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password'
    }))

    class Meta:
        model = User
        fields = ('full_name', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)

        for field_name, filed in self.fields.items():
            filed.widget.attrs['class'] = 'text-field-imput w-input'

class CustomSetPasswordForm(SetPasswordForm):
    error_messages = {
        'password_mismatch': _('The two password fields didn’t match.'),
    }
    new_password1 = forms.CharField(
        strip=False,
        label='',
        widget=forms.PasswordInput(attrs={
            'placeholder': 'New password',
        }),
    )
    new_password2 = forms.CharField(
        strip=False,
        label='',
        widget=forms.PasswordInput(attrs={
            'placeholder': 'New password confirmation'
        }),
    )
    def __init__(self, *args, **kwargs):
        super(CustomSetPasswordForm, self).__init__(*args, **kwargs)

        for field_name, filed in self.fields.items():
            filed.widget.attrs['class'] = 'text-field-imput w-input'

class ResetPasswordForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(ResetPasswordForm, self).__init__(*args, **kwargs)

        for field_name, filed in self.fields.items():
            filed.widget.attrs['class'] = 'text-field-imput w-input'

user/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect, HttpResponse
from django.urls import reverse
from django.contrib import auth, messages
from .forms import UserLoginForm, UserRegistrationForm, PasswordResetForm, CustomSetPasswordForm

from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage, send_mail
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordResetConfirmView

# from django.contrib.sites.models import Site

from django.db.models.query_utils import Q
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import FormView, PasswordContextMixin
from decouple import config

from .tokens import account_activation_token
from user.models import User

def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except:
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        messages.success(request, "Thank you for your email confirmation. Now you can login your account.")
        return redirect('user:login')
    else:
        messages.error(request, "Activate link is invalid!")

    return redirect('user:login')

def activateEmail(request, user, to_email):
    # user = User.objects.get(email=to_email)

    subject = 'Activate your user account.'
    email_template_name = 'user/template_activate_account.html'

    cont = {
        'email': user.email,
        # 'domain': get_current_site(request).domain,
        'domain': config('PRIMARY_DOMAIN'),
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'user': user,
        'token': account_activation_token.make_token(user),
        'protocol': 'https' if request.is_secure() else 'http'
    }
    msg_html = render_to_string(email_template_name, cont)
    try:
        send_mail(subject, 'Link', 'noreply@askaaron.app', [user.email], fail_silently=True, html_message=msg_html)
        messages.success(request, f'Dear {user.full_name}, please go to you email {to_email} inbox and click on '
                                  f'received activation link to confirme and complete the registration. Note: Check your spam folder.')
    except Exception:
        messages.error(request, f'Problem sending email to {to_email}, check if you typed it correctly.')

def login(request):
    user = request.user
    if user.is_authenticated:
        return redirect('ask_chat:ask_anything')
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        # if form.is_valid():
        email = request.POST['email']
        password = request.POST['password']
        if not User.objects.filter(email=email).exists():
            messages.error(request, 'Email or Password Is Not Correct')
        else:
            user = auth.authenticate(email=email, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('ask_chat:ask_anything'))
            else:
                return HttpResponseRedirect(reverse('user:login'))
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'user/login.html', context)

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.is_superuser = False
            user.is_staff = False
            user.save()
            activateEmail(request, user, form.cleaned_data.get('email'))
            return redirect('user:login')
        else:
            for error in list(form.errors.values()):
                messages.error(request, error)

    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'user/register.html', context)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))


def password_reset_request(request):
    if request.method == 'POST':
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            user_email = form.cleaned_data['email']
            try:
                user = User.objects.get(email=user_email)
            except Exception:
                user = False
            if user:
                subject = 'Request reset password'
                email_template_name = 'user/reset_password_email.html'

                cont = {
                    'email': user.email,
                    # 'domain': get_current_site(request).domain,
                    'domain': config('PRIMARY_DOMAIN'),
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'user': user,
                    'token': default_token_generator.make_token(user),
                    'protocol': 'https' if request.is_secure() else 'http'
                }
                msg_html = render_to_string(email_template_name, cont)
                try:
                    send_mail(subject, 'Link', 'noreply@askaaron.app', [user.email], fail_silently=True, html_message=msg_html)
                except Exception:
                    return HttpResponse('Invalid Header')
                return redirect('password_reset_done')
            else:
                messages.error(request, "User not found")
                return redirect('reset_password')
    return render(request, template_name='user/password_reset.html')
class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    form_class = CustomSetPasswordForm
    template_name = 'user/password_reset_confirm.html'



def custom_page_not_found_view(request, exception):
    return render(request, "user/404.html", {})

# def custom_error_view(request, exception=None):
#     return render(request, "errors/500.html", {})
#
# def custom_permission_denied_view(request, exception=None):
#     return render(request, "errors/403.html", {})
#
# def custom_bad_request_view(request, exception=None):
#     return render(request, "errors/400.html", {})

user/templates/user/login.html
{% extends 'ask_chat/base.html' %}
{% load static %}

{% block content %}
    <div data-animation="default" data-collapse="medium" data-duration="400" data-easing="ease" data-easing2="ease" role="banner" class="navbar-2 w-nav">
    <div class="container-4 w-container">
      <nav role="navigation" class="nav-menu w-nav-menu">
{#        <a href="../../../ask_chat/templates/ask_chat/index.html" class="nav-link w-nav-link">Home</a>#}
{#        <a href="#" class="nav-link w-nav-link">About</a>#}
{#        <a href="#" class="nav-link w-nav-link">Log In</a>#}
      </nav>
      <div class="menu-button-2 w-nav-button">
        <div class="w-icon-nav-menu"></div>
      </div>
      <a href="{% url 'index' %}" class="brand w-nav-brand">
        <div class="text-block-2">ASK AARON</div><img src="{% static 'images/logo-icon-pink.svg' %}" alt="logo icon" class="image-2">
      </a>
    </div>
  </div>
  <div class="section-3 wf-section">
    <div class="container-5 w-container">
      <div class="divformregister">
        <div class="w-layout-grid grid-3">
            {% for message in messages %}
                <div id="w-node-_8352cabb-5576-8709-76e6-3cf7cf4aaa98-e508d18b" class="text-under-header">{{ message }}</div>
            {% endfor %}
            <div id="w-node-_8352cabb-5576-8709-76e6-3cf7cf4aaa98-e508d18b" class="text-under-header">Please enter your Email &amp; Password</div>
            <h1 id="w-node-_9c377abd-253c-3cf6-7e42-db86ee020ff7-e508d18b" class="heading-3">LOGIN</h1>
            <div id="w-node-a02d591c-a5dc-8ca2-545d-3967d27d80a8-e508d18b" class="w-form">
            <form action="{% url 'user:login' %}" id="email-form" name="email-form" data-name="Email Form" method="post" class="form-3">
                {% csrf_token %}
{#                <input type="email" class="text-field-imput w-input" maxlength="256" name="email" data-name="Email" placeholder="Your Email" id="email" required="">#}
                {{ form.email }}

{#                <input type="password" class="text-field-imput w-input" maxlength="256" name="password" data-name="Field" placeholder="Password" id="field" required="">#}
                {{ form.password }}

              <a href="{% url 'user:password_reset' %}" class="link-block w-inline-block">
                <div class="forgot-pass">Forgot Password</div>
              </a><input type="submit" value="Login" data-wait="Please wait..." class="submit-button-5 w-button">
            </form>
            <div class="w-form-done">
              <div>Thank you! Your submission has been received!</div>
            </div>
            <div class="w-form-fail">
              <div>Oops! Something went wrong while submitting the form.</div>
            </div>
          </div>
          <div id="w-node-_13d4496f-eaec-3ec0-f34a-103e5d1c7024-e508d18b" class="text-account">Don’t have an account yet?</div>
          <a id="w-node-b7e71c4f-a1df-c3d1-d1e6-81f52f75796f-e508d18b" href="{% url 'user:register' %}" class="w-inline-block">
            <div class="log-in">Register</div>
          </a>
        </div>
      </div>
    </div>
  </div>
  <div class="section-2 wf-section">
    <div class="container-3 w-container">
      <div class="text-footer white">Copyright © 2023 <span class="text-span-4">AskAaron.app </span>/Lawsity LLC | All Right Reserved.</div>
    </div>
  </div>

{% endblock %}

user/templates/user/password_reset.html
{% extends 'ask_chat/base.html' %}
{% load static %}

{% block content %}
{#    {% load crispy_forms_tags %}#}
    <div data-animation="default" data-collapse="medium" data-duration="400" data-easing="ease" data-easing2="ease" role="banner" class="navbar-2 w-nav">
    <div class="container-4 w-container">
      <nav role="navigation" class="nav-menu w-nav-menu">
{#        <a href="../../../ask_chat/templates/ask_chat/index.html" class="nav-link w-nav-link">Home</a>#}
{#        <a href="#" class="nav-link w-nav-link">About</a>#}
        <a href="{% url 'user:login' %}" class="nav-link w-nav-link">Log In</a>
      </nav>
      <div class="menu-button-2 w-nav-button">
        <div class="w-icon-nav-menu"></div>
      </div>
      <a href="{% url 'index' %}" class="brand w-nav-brand">
        <div class="text-block-2">ASK AARON</div><img src="{% static 'images/logo-icon-pink.svg' %}" alt="logo icon" class="image-2">
      </a>
    </div>
  </div>
  <div class="section-3 wf-section">
    <div class="container-5 w-container">
      <div class="divformregister">
        <div class="w-layout-grid grid-3">
          <h1 id="w-node-_9c377abd-253c-3cf6-7e42-db86ee020ff7-983adbeb" class="heading-3">Forgot<br>RESET PASSWORD</h1>
          <div id="w-node-_8352cabb-5576-8709-76e6-3cf7cf4aaa98-983adbeb" class="text-under-header">Please enter your Email:</div>
          <div id="w-node-a02d591c-a5dc-8ca2-545d-3967d27d80a8-983adbeb" class="w-form">
            <form action="{% url 'user:password_reset' %}" id="email-form" name="email-form" data-name="Email Form" method="POST" class="form-3">
                {% csrf_token %}
                <input type="email" class="text-field-imput w-input" maxlength="256" name="email" data-name="Email" placeholder="Your Email" id="email" required="">
{#                {{ form }}#}
                <input type="submit" value="Submit" data-wait="Please wait..." class="submit-button-5 w-button">
            </form>
            <div class="w-form-done">
              <div>Thank you! Your submission has been received!</div>
            </div>
            <div class="w-form-fail">
              <div>Oops! Something went wrong while submitting the form.</div>
            </div>
          </div>
          <div id="w-node-_13d4496f-eaec-3ec0-f34a-103e5d1c7024-983adbeb" class="text-account">Don’t have an account yet?</div>
          <a id="w-node-b7e71c4f-a1df-c3d1-d1e6-81f52f75796f-983adbeb" href="{% url 'user:register' %}" class="w-inline-block">
            <div class="log-in">Register</div>
          </a>
        </div>
      </div>
    </div>
  </div>
  <div class="section-2 wf-section">
    <div class="container-3 w-container">
      <div class="text-footer white">Copyright © 2023 <span class="text-span-4">AskAaron.app </span>/Lawsity LLC | All Right Reserved.</div>
    </div>
  </div>


{% endblock %}

user/templates/user/password_reset_confirm.html
{% load static %}
<!DOCTYPE html><!--  This site was created in Webflow. https://www.webflow.com  -->
<!--  Last Published: Tue Jan 24 2023 07:48:52 GMT+0000 (Coordinated Universal Time)  -->
<html data-wf-page="63cb76e2d7632eb7e133dd37" data-wf-site="63c71f3c4e03650f2016f4d7" lang="en">
<meta charset="utf-8">
<title>AskAaron.app your AI-powered Lawyer | Lawsity</title>
<meta content="AskAaron.app is your AI-powered Lawyer developed by Lawsity, capable of generating human-like answers." name="description"/>
<meta content="AskAaron.app your AI-powered Lawyer | Lawsity" property="og:title"/>
<meta content="AskAaron.app is your AI-powered Lawyer developed by Lawsity, capable of generating human-like answers." property="og:description"/>
<meta content="https://askaaron.app/static/images/ask-aaron-logo.png" property="og:image"/>
<meta content="AskAaron.app your AI-powered Lawyer | Lawsity" property="twitter:title"/>
<meta content="AskAaron.app is your AI-powered Lawyer developed by Lawsity, capable of generating human-like answers." property="twitter:description"/>
<meta content="https://askaaron.app/static/images/ask-aaron-logo.png" property="twitter:image"/>
<meta content="width=device-width, initial-scale=1" name="viewport">
<meta property="og:type" content="website"/>
<meta content="summary_large_image" name="twitter:card"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<link href="https://askaaron.app/static/images/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="https://askaaron.app/static/images/ask-aaron-logo.png" rel="apple-touch-icon"/>
    <!-- meta title -->
    <meta content="AskAaron.app your AI-powered Lawyer | Lawsity" property="twitter:title">
    <!-- end meta title -->
    <!-- meta description -->
    <meta content="AskAaron.app is your AI-powered Lawyer developed by Lawsity, capable of generating human-like answers." property="twitter:description">
    <!-- end meta description -->
    <!-- meta optional -->
    <meta property="og:site_name" content="AskAaron.app"/>
<link rel="shortcut icon" type="image/x-icon" href="https://askaaron.app/static/images/favicon.ico"/>
<meta property="og:image" content="https://askaaron.app/static/images/ask-aaron-logo.png"/>
<meta property="og:image:secure_url" content="https://askaaron.app/static/images/ask-aaron-logo.png"/>
<meta name="twitter:image" content="https://askaaron.app/static/images/ask-aaron-logo.png"/>
    <!-- end meta optional -->
    <!-- meta image -->
        <meta property="og:image" content="https://askaaron.app/static/images/ask-aaron-logo.png">
    <meta property="og:image:secure_url" content="https://askaaron.app/static/images/ask-aaron-logo.png">
    <meta name="twitter:image" content="https://askaaron.app/static/images/ask-aaron-logo.png">
    <!-- end meta image -->
    <!-- end meta script -->
    <meta property="og:type" content="website">
    <meta content="summary_large_image" name="twitter:card">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <!--  meta default  -->
    <meta property="og:type" content="website">
    <meta content="summary_large_image" name="twitter:card">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta property="og:locale" content="en_US">
    <meta property="og:site_name" content="askaaron.app">
    <meta name="theme-color" content="#545974">
    <link href="{% static 'css/normalize.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/webflow.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/chatgpt-876e64.webflow.css' %}" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
    <script type="text/javascript">
        WebFont.load({
        google: {
            families: ["Rubik:200,300,400,500,600,700"]
        }
        });
    </script>
    <!-- [if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script><![endif] -->
    <script type="text/javascript">
        ! function(o, c) {
        var n = c.documentElement,
            t = " w-mod-";
        n.className += t + "js", ("ontouchstart" in o || o.DocumentTouch && c instanceof DocumentTouch) && (n.className += t + "touch")
        }(window, document);
    </script>
    <link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">
    <link href="{% static 'images/webclip.png' %}" rel="apple-touch-icon">
</head>
<body class="body-2">


    <div data-animation="default" data-collapse="medium" data-duration="400" data-easing="ease" data-easing2="ease" role="banner" class="navbar-2 w-nav">
        <div class="container-4 w-container">
{#          <nav role="navigation" class="nav-menu w-nav-menu">#}
{#            <a href="../../../ask_chat/templates/ask_chat/index.html" class="nav-link w-nav-link">Home</a>#}
{#            <a href="#" class="nav-link w-nav-link">About</a>#}
{#            <a href="#" class="nav-link w-nav-link">Log In</a>#}
{#          </nav>#}

          <a href="{% url 'index' %}" class="brand w-nav-brand">
            <div class="text-block-2">ASK AARON</div><img src="{% static 'images/logo-icon-pink.svg' %}" alt="logo icon" class="image-2">
          </a>
        </div>
    </div>
  <div class="section-3 wf-section">
    <div class="container-5 w-container">
      <div class="divformregister">
        <div class="w-layout-grid grid-3">
            <div id="w-node-_8352cabb-5576-8709-76e6-3cf7cf4aaa98-e508d18b" class="text-under-header">Please enter your Email &amp; Password</div>
                <h1 id="w-node-_9c377abd-253c-3cf6-7e42-db86ee020ff7-e508d18b" class="heading-3">RESET PASSWORD CONFIRM</h1>
                <div id="w-node-a02d591c-a5dc-8ca2-545d-3967d27d80a8-e508d18b" class="w-form">

                        <form method="post" id="email-form" name="email-form" data-name="Email Form" class="form-3">
                            {% csrf_token %}
                            {{ form }}
                            <input type="submit" value="Submit" data-wait="Please wait..." class="submit-button-5 w-button">
                        </form>

                    <div class="w-form-done">
                      <div>Thank you! Your submission has been received!</div>
                    </div>
                    <div class="w-form-fail">
                      <div>Oops! Something went wrong while submitting the form.</div>
                    </div>
                </div>
{#            <div id="w-node-_13d4496f-eaec-3ec0-f34a-103e5d1c7024-e508d18b" class="text-account">Don’t have an account yet?</div>#}
{#          <a id="w-node-b7e71c4f-a1df-c3d1-d1e6-81f52f75796f-e508d18b" href="{% url 'user:register' %}" class="w-inline-block">#}
            <div class="log-in">Register</div>
          </a>
        </div>
      </div>
    </div>
  </div>
  <div class="section-2 wf-section">
    <div class="container-3 w-container">
      <div class="text-footer white">Copyright © 2023 <span class="text-span-4">AskAaron.app </span>/Lawsity LLC | All Right Reserved.</div>
    </div>
  </div>

  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=63c71f3c4e03650f2016f4d7" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
{#  <script src="{% static 'js/webflow.js' %}" type="text/javascript"></script>#}
  <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->
</body>
</html>

user/templates/user/template_activate_account.html
{% autoescape off %}
Hello, {{ user.full_name }},

Please click on the link below to confirm your registration:<br>
    <a href="{{ protocol }}://{{ domain }}{% url 'user:activate' uidb64=uid token=token %}">Confirmation Link</a><br>
{% endautoescape %}